name: Non-Functional Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven

      - name: Run Non-Functional Tests
        run: mvn test -Dtest=mk.finki.ukim.mk.lab.nonFunctional.*Tests


      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: non-functional-test-reports
          path: target/surefire-reports/
